name: Cargo build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build -p r-extcap -p extcap-example --verbose
    - name: Run tests
      run: cargo test -p r-extcap -p extcap-example --verbose
